services:
    jhome.permissions.loader:
        class: Jhome\PermissionsBundle\Loader\YamlPermissionsLoader
        arguments: [%kernel.bundles%, %kernel.root_dir%]
        public: false
    jhome.permissions.voter:
        class: Jhome\PermissionsBundle\Voter\PermissionsVoter
        arguments: [@jhome.permissions.loader, @security.access.expression_voter]
        public: false
        tags:
           - { name: security.voter }
