services:
    jhome.permissions.loader:
        class: Jhome\PermissionsBunble\Loader\YamlPermissionsLoader
        public: false
    jhome.permissions.voter:
        class: Jhome\PermissionsBundle\Voter\PermissionsVoter
        arguments: [@jhome.permissions.loader, @security.access.expression_voter]
        public: false
        tags:
           - { name: security.voter }
